Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/ipyautoui-dev/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import typing as ty
from pydantic import BaseModel, Field
from ipyautoui import AutoUi


class DataFrameCols(BaseModel):
    string: str = Field("string", aui_column_width=100)
    integer: int = Field(1, aui_column_width=80)
    floater: float = Field(3.1415, aui_column_width=70, global_decimal_places=3)
    something_else: float = Field(324, aui_column_width=100)


class TestDataFrame(BaseModel):
    """a description of TestDataFrame"""

    dataframe: ty.List[DataFrameCols] = Field(
        default_factory=lambda: [], format="dataframe"
    )
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m [38;5;21;01mtyping[39;00m [38;5;28;01mas[39;00m [38;5;21;01mty[39;00m
[1;32m      2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpydantic[39;00m [38;5;28;01mimport[39;00m BaseModel, Field
[0;32m----> 3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mipyautoui[39;00m [38;5;28;01mimport[39;00m AutoUi
[1;32m      6[0m [38;5;28;01mclass[39;00m [38;5;21;01mDataFrameCols[39;00m(BaseModel):
[1;32m      7[0m     string: [38;5;28mstr[39m [38;5;241m=[39m Field([38;5;124m"[39m[38;5;124mstring[39m[38;5;124m"[39m, aui_column_width[38;5;241m=[39m[38;5;241m100[39m)

[0;31mModuleNotFoundError[0m: No module named 'ipyautoui'
ModuleNotFoundError: No module named 'ipyautoui'

